config/routes.rb
Combobuilder::Application.routes.draw do
  resources :parsed_combos, :only => [ :show ], constraints: { id: /[\w|\!|\@|\$]+/ }
  resources :combos, :only => [ :show, :new, :edit ]
  root 'home#index'

  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/combos_controller.rb
require 'combobuilder'

class CombosController < ApplicationController
  def new
    @input_schemes = ComboBuilder::input_schemes
    @combo = ''
  end

  def edit
    @input_schemes = ComboBuilder::input_schemes
    @combo = ComboBuilder.decode(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    redirect_to new_combo_url
  end
end

app/controllers/parsed_combos_controller.rb
require 'combobuilder'

class ParsedCombosController < ApplicationController
  def show
    info = params[:id]
    @no_layout = !params[:no_layout].nil?
    if info =~ /(.*)\$(.*)/
      @scheme = ComboBuilder.input_schemes[$~.captures[0]]
      if @scheme.nil?
        @nodes = [ComboBuilder::ErrorNode.new('Unknown input scheme')]
      else
        combo = $~.captures[1].gsub(/[!|@]/) { |c| (c == '!' ? '.' : ' ') }
        @nodes = ComboBuilder::Parser.parse(@scheme, combo)
      end
    else
      @nodes = [ComboBuilder::ErrorNode.new('Invalid combo string')]
    end

    @errors = @nodes.select { |n| n.type == :error }
    respond_to do |format|
      format.html { render layout: false  }
      format.json { render :json => @nodes }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/combos_helper.rb
module CombosHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/parsed_combos_helper.rb
module ParsedCombosHelper

  def display_part(scheme, part)
    if scheme.display_overrides.has_key?(part.to_sym)
      return scheme.display_overrides[part.to_sym]
    end

    "<img src=\"#{image_path('moves/' + part + '.png')}\" />"
  end

end

app/views/combos/_comboeditor.html.erb
<div class="hide" data-bind="css: { hide: !browserSupported() }">
  <form class="form-horizontal">
    <div class="control-group">
      <label class="control-label" for="inputScheme">Input Scheme</label>

      <div class="controls">
        <select id="inputScheme"
                data-bind="options: inputSchemes, optionsText: 'title', value: selectedInputScheme">
        </select>
      </div>
    </div>
    <div class="control-group">
      <label class="control-label" for="comboText">Combo Input</label>

      <div class="controls">
        <input id="comboText" type="text" data-bind="value: comboText, valueUpdate: 'afterkeydown'"/>
      </div>
    </div>

    <div class="control-group">
      <label class="control-label">Combo</label>
      <div class="controls">
        <div class="well combo-well">
          <div>
            <input id="comboLink" type="text" data-bind="value: comboLink" readonly="true" />
          </div>
          <div data-bind="html: combo"></div>
        </div>
        <div class="alert alert-error hide" data-bind="html: errorMessage, css: { hide: !hasError() }"></div>
      </div>
    </div>
  </form>
</div>

<% content_for :scripts do %>
    <%= javascript_include_tag('combobuilder') %>
    <script type="text/javascript">
        window.comboBuilder = window.comboBuilder || {};
        window.comboBuilder.inputSchemes = [
            <% input_schemes.each do |key, value| %>
            { name: '<%= key %>', title: '<%= value.title %>' },
            <% end %>
        ];

        window.comboBuilder.parsedComboUrl = '<%= (parsed_combo_url(:id => '$'))[0..-2] %>';
        window.comboBuilder.comboUrl = '<%= (combo_url(:id => '$'))[0..-2] %>';

        $(function () {
            ko.applyBindings(new ComboBuilderViewModel());
        });
    </script>
<% end %>

app/views/combos/edit.html.erb
<%= render :partial => 'comboeditor', :locals => { :input_schemes => @input_schemes }  %>

app/views/combos/new.html.erb
<%= render :partial => 'comboeditor', :locals => { :input_schemes => @input_schemes } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Combobuilder</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="center-content">
  <%= yield %>
</div>

<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<script type="text/javascript">
  if(supportsEcma5()) {
      $('head').append("<script type='text/javascript' src='<%= javascript_url('harmony') %>'>");
  }
</script>
<%= yield :scripts %>

</body>
</html>

app/views/parsed_combos/show.html.erb
<% unless @no_layout %>
<!DOCTYPE html>
<html>
<head>
  <title>Combobuilder</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
</head>
<body>
<% end %>
<% if !@errors.empty? %>
<div class="alert alert-error">
  <ul>
        <% @errors.each do |error| %>
    <%= raw(error.message) %>
        <% end %>
  </ul>
</div>
<% else %>
    <% @nodes.each do |node| %>
<span class="combo-part">
    <% if node.has_modifier? %>
    <%= raw(display_part(@scheme, node.modifier)) %>
    <% end %>
    <% node.parts.each do |part| %>
    <%= raw(display_part(@scheme, part)) %>
    <% end %>
</span>
    <% end %>
<% end %>

<% unless @no_layout %>
</body>
<% end %>